# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8cb7dcf1cc2b89196bad69bc30f4d157"
name = "testing-app-v1"
handle = "testing-app-v1-1"
application_url = "https://seven-joel-conditional-prayers.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "testing-app-v1.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://seven-joel-conditional-prayers.trycloudflare.com/auth/callback",
  "https://seven-joel-conditional-prayers.trycloudflare.com/auth/shopify/callback",
  "https://seven-joel-conditional-prayers.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
